.TH MARTWM 1 martwm-VERSION
.SH NAME
martwm \- Martin's Mouse Driven Tiling Window Manager
.SH SYNOPSIS
.B martwm
.SH DESCRIPTION
.B martwm
is a mouse driven tiling window manager for X.
.SH USAGE
.SS Mouse commands
.TP
.B Mod4\-Button1
Move focused window while dragging.
.TP
.B Mod4\-Button3
Resize focused window while dragging.
.SS Keyboard Commands
.TP
.B Mod4\-Shift\-e
Exit window manager
.TP
.B Mod4\-Shift\-q
Quit window
.TP
.B Mod4\-a
Raise window
.TP
.B Mod4\-b
Toggle status bar
.TP
.B Mod4\-d
Opens dmenu

.SH CUSTOMIZATION
TODO

.SH SEE ALSO
.BR dmenu (1).

.SH BUGS
Send all bug reports to the GitHub issues page: https://github.com/marttcw/martwm/issues

